[[redirects]]
  from = "/grafana/*"
  to = "https://grafana.nixos.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/prometheus/*"
  to = "https://prometheus.nixos.org/:splat"
  status = 200
  force = true
